### ISSUE TITLE
Extension: Share on icons overlay existing post button icons.

### ISSUE THREAD

**Issue by steveurkel123** [vinny/Share-On#13]
As described in https://www.phpbb.com/community/viewtopic.php?p=13770111#p13770111 the share on icons overlay the standard post button icons.

![image](https://cloud.githubusercontent.com/assets/9503331/4873224/aabdaef4-6206-11e4-9a1f-9951a9fb030d.png)

This is for the 3.1 extension.

**Comment by vinny** [comment]
Fixed: https://github.com/vinny/Share-On/commit/ce7275a9a1ce530c96a649bb5beebc8e7393c8a1#diff-6
