### ISSUE TITLE
Problem phpbb 3.1.X

### ISSUE THREAD

**Issue by Amaury123** [vinny/share-on#18]
Hi Vinny,

I contact you because since 1 year, I have upgraded to the version 3.1 of phpbb.
Otherwise, I still have your extension "share on" for the version 3.0 of phpbb on my ftp. For example I still have the "acp_shaeron.php" file. But I want to delete all the extension, because now I have this error in my acp:
```Fatal error: Uncaught exception 'phpbb\exception\runtime_exception' with message 'FILE_NOT_FOUND' in /home/fmeurope/public_html/forum/phpbb/file_downloader.php:72 Stack trace: #0 /home/fmeurope/public_html/forum/includes/functions_admin.php(3057): phpbb\file_downloader->get('www.suportephpb...', '/shareon', 'shareon.txt', 80, 6) #1 /home/fmeurope/public_html/forum/includes/acp/acp_shareon.php(107): get_remote_file('www.suportephpb...', '/shareon', 'shareon.txt', '', 0) #2 /home/fmeurope/public_html/forum/includes/acp/acp_shareon.php(86): acp_shareon->shareon_version_compare('2.2.0') #3 /home/fmeurope/public_html/forum/includes/functions_module.php(674): acp_shareon->main('shareon', 'index') #4 /home/fmeurope/public_html/forum/adm/index.php(81): p_master->load_active() #5 {main} thrown in /home/fmeurope/public_html/forum/phpbb/file_downloader.php on line 72```

So If you can help me.

Amaury.

**Comment by Galixte** [comment]
Salut @Amaury123,

bien joué. ;)

Deux remarques pour insérer du code dans les messages sur GitHub, utilise la combinaison des touches Alt Gr + 7 ce qui donne ce caractère :
```
`
```
Il t’en faut trois pour ouvrir la balise code et trois pour la terminer, soit : 
```
```ton code```
```

Deuxièmenent, on dit : ```Otherwise``` sans le H entre W et I.

**Comment by Amaury123** [comment]
Merci @Galixte 
Oui, j'ai répondu vite sans faire attention à mon orthographe, mais tu as raison.

Merci pour l'astuce pour le code, merci.

**Comment by vinny** [comment]
First, delete the files:
root/includes/acp/acp_shareon.php
root/includes/acp/info/acp_shareon.php

Now, remove Share On MOD module from your board, follow the steps:

If you have not added any extensions you can remove non standard modules and permissions by:
1. <b>Make sure you make a backup of your database before proceeding.</b>
2. Uploading this file, <a href="https://app.box.com/s/9y2jwc7elzj3ox8q8j2m">modission_reset.php</a>, to the root of your board installation on the server.
3. Log into the board as a founder and/or admin.
4. Navigate your browser to the file, for example <code>http://www.example.com/example_forum/modission_reset.php</code>
5. Choose modules and permissions and run the file
6. It will tell you how many modules and permissions it deletes, or may give you some other message if all is not well. Make a note of that.
7. It should automatically delete itself from the server, if it can't it will tell you.


About step 5, choose Share On MOD to remove.

If you have any question, let me know.

**Comment by Galixte** [comment]
Salut @Amaury123,

tu devrais clore ce ticket d’incident, et surtout changer les titres pour qu’il soit indéxer sur Google et que les utilisateurs retrouvent facilement ce guide. Le titre pourrait-être : « Remove Share On MOD module ».
