### ISSUE TITLE
Facebook Share

### ISSUE THREAD

**Issue by Galixte** [vinny/share-on#21]
Hi @vinny,

on phpBB-fr.com a user reports to me a problem about Facebook sharing.

If he shares a post from a topic, there is not:
- the image from the post shared but from the footer (cosmetic image),
- the good link from the post shared but to the index link (./index.php),
- the message from the post shared but from the home page.

Is it the normal behaviour ?

**Comment by Galixte** [comment]
Hi @vinny,

could you take a look, please ?

**Comment by vinny** [comment]
> the good link from the post shared but to the index link (./index.php),

The extension works fine for links.


>  the image from the post shared but from the footer (cosmetic image),
 >   the message from the post shared but from the home page.

this is normal, because I did not implement opengraph and meta tags.

**Comment by Galixte** [comment]
Thanks for informations !
