### ISSUE TITLE
phpBB 3.2.x version

### ISSUE THREAD

**Issue by Galixte** [vinny/share-on#25]
Hi @vinny,

could you take a look about compatibility with phpBB 3.2.x, please ?

**Comment by vinny** [comment]
The latest 3.1 version [works](https://www.phpbb.com/customise/db/extension/shareon/support/topic/169671?p=533111#p533111) on 3.2.

But I want to develop a fully compatible version with 3.2. I will give more news soon.

**Comment by Galixte** [comment]
Thanks 👍

**Comment by vinny** [comment]
@Galixte I just finished version 2.0.1 to 3.1.10, I'm waiting for the translations (new and updated). 

Then I'll submit it to the CBD. After submit, I'll start the version for 3.2.0. 👍

**Comment by Galixte** [comment]
Thanks ! I’ll keep an eye on your work. 👍
