### ISSUE TITLE
All share options share login page not article

### ISSUE THREAD

**Issue by thetgc** [vinny/share-on#29]
Using on phpbb 3.2 and was fine until yesterday when suddenly all I can share is the site login page. Have tried disabling, deleting date, removing extension, downloading latest version from GitHub and installing etc but same issue. Can't figure out what has gone wrong.

**Comment by vinny** [comment]
Make sure that bots and guests are allowed to view and read the forums where the topics were created.

**Comment by vinny** [comment]
Post your questions here: https://www.phpbb.com/customise/db/extension/shareon/support
